language: node_js
  - "node"

stages:
  - name: test
  - name: build
    if: branch = "master"

jobs:  
  include:
    - stage: test
      script: ./bin/test.sh
    - stage: build
      script:
        - npm --force install tiddlywiki
        - export GIT_DETAILS="$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse HEAD) from $(git remote get-url origin)"
        - export TW5_BUILD_TIDDLYWIKI='./node_modules/tiddlywiki/tiddlywiki.js'
        - ./bin/build-site.sh
        - ./bin/deploy-site.sh
