language: node_js
  - "node"

stages:
  - name: test
  - name: build
    if: branch = "master"

jobs:  
  include:
    - stage: test
      script: ./bin/test.sh
    - stage: build
      script:
        - ./bin/travis-pre-build.sh
        - export TW5_BUILD_DETAILS="Built from branch '$TRAVIS_BRANCH' at commit $(git rev-parse HEAD) of $(git remote get-url origin) at $(date '%H:%M:%S +%Y-%m-%d')"
        - export TW5_BUILD_TIDDLYWIKI='./node_modules/tiddlywiki/tiddlywiki.js'
        - ./bin/build-site.sh
        - ./bin/travis-push.sh
